#!/bin/sh
# $Id$
# elvis: acronym		-- Look for acronyms definitions (www.acronymfinder.com)
. surfraw || exit 1

w3_config_hook () {
    def SURFRAW_acronym_category All
    def SURFRAW_acronym_match exact
    defyn SURFRAW_acronym_ran 0
    defyn SURFRAW_acronym_gen 0
    defyn SURFRAW_acronym_alpha 0
    defyn SURFRAW_acronym_attic 0
    def   SURFRAW_acronym_path
    def   SURFRAW_acronym_par

}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [option] [keyword]
Description:
  Surfraw searches for possible definitions of acronyms using acronymfinder.com
Local option:
  -i -ict              List all acronyms matching in Information Technology category
  -s -sci	       List all acronyms matching in Science & Medicine category
  -g -gov	       List all acronyms matching in Government & Military category
  -o -org              List all acronyms matching in Organizations & Schools category
  -b -biz              List all acronyms matching in Business & Finance category
  -c -common	       List all acronyms matching in Slang & Pop Culture category
  -e -exact            List all acronyms matching with exact match (Default when keyword specified)
  -w -wim              List all acronyms matching with Word(s) in meaning match
  -z -zip              List all acronyms matching with Location (postal code, name) match
  -r -random           List a random acronym (Default when no keyword specified)
  -f -fake	       List a fake acronym generated with the Acronym Finder Random Systematic Buzz Phrase Projector (AFRSBPP)
  -a -alphabetic       List all acronyms matching sorted alphabetically instead of by rank
  -u -unverified       List all acronyms matching, included those unverified by men and potentially misleading (Acronym Attic)



EOF
    w3_global_usage
}
mkopts ict sci gov org biz common exact wim zip random fake alphabetic unverified

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
#Information Technology category
    -i|-ict)	setopt SURFRAW_acronym_category "IT" ;;
#Science & Medicine category
    -s|-sci)	setopt SURFRAW_acronym_category "SciMed" ;;
#Government & Military category
    -g|-gov)	setopt SURFRAW_acronym_category "MilGov" ;;
#Organizations & Schools category
    -o|-org)	setopt SURFRAW_acronym_category "Org" ;;
#Business & Finance category
    -b|-biz)	setopt SURFRAW_acronym_category "Business" ;;
#Slang & Pop Culture category
    -c|-common)	setopt SURFRAW_acronym_category "Slang" ;;
#exact match
    -e|-exact)	setopt SURFRAW_acronym_match "exact" ;;
#Word(s) in meaning match
    -w|-wim)	setopt SURFRAW_acronym_match "on" ;;
#Location (postal code, name) match
    -z|-zip)	setopt SURFRAW_acronym_match "zip" ;;
#Random acronym
    -r|-random)        setoptyn SURFRAW_acronym_ran   1
	        setoptyn SURFRAW_acronym_gen   0 ;;
#Fake acronym
    -f|-fake)        setoptyn SURFRAW_acronym_gen   1
	        setoptyn SURFRAW_acronym_ran   0 ;;
#Sort alphabetically
    -a|-alphabetic)	setoptyn SURFRAW_acronym_alpha  1 ;;
#Match from Acronym Attic
    -u|-unverified)	setoptyn SURFRAW_acronym_attic  1 ;;

    *) 		return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments

if test -z "$w3_args"; then
    if [ "$SURFRAW_acronym_gen" = 1 ]; then
	SURFRAW_acronym_path="http://www.acronymfinder.com/buzzgen.asp" # Fake Acronym
    else SURFRAW_acronym_path="http://www.acronymfinder.com/random.aspx"     # Random Acronym
    fi
else
     escaped_args=$(w3_url_of_arg $w3_args)
     if	[ "$SURFRAW_acronym_attic" = 1 ]; then
	SURFRAW_acronym_path="http://www.acronymattic.com/~/search/aa.aspx?Acronym=" # Acronym Attic
     else
	SURFRAW_acronym_path="http://www.acronymfinder.com/~/search/af.aspx?Acronym=" # Acronym Finder
	SURFRAW_acronym_par="&Find=find&string=${SURFRAW_acronym_match}&Page=1"
	SURFRAW_acronym_par="$SURFRAW_acronym_par&Category=${SURFRAW_acronym_category}"
     fi
     if [ "$SURFRAW_acronym_alpha" = 1 ]; then
	SURFRAW_acronym_par="$SURFRAW_acronym_par&s=a"
     fi
fi
w3_browse_url "$SURFRAW_acronym_path${escaped_args}$SURFRAW_acronym_par"

