#!/bin/sh
# $Id$
# elvis: cite		-- Search computer science papers (citeseerx.ist.psu.edu)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
   Surfraw search CiteSeer^X (citeseerx.ist.psu.edu)

   CiteSeer is a scientific literature digital library that
   indexes the full text of spidered PDF and PS documents and performes
   sophisticated clustering and citation analysis on the results.
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://citeseerx.ist.psu.edu/"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    # It's hard to find what the query parameters are, so we can't configure the sorting.
    url="https://citeseerx.ist.psu.edu/search_result?query=${escaped_args}&pdf=true"
    w3_browse_url "$url"
fi
