#!/bin/sh
# $Id$
# elvis: lemoteur	-- Search the web using lemoteur.fr
. surfraw || exit 1

w3_config_hook () {
		def   SURFRAW_lemoteur_results "$SURFRAW_results"
		def   SURFRAW_lemoteur_search search
		defyn SURFRAW_lemoteur_lucky 0
		def   SURFRAW_lemoteur_country us
		def   SURFRAW_lemoteur_safe default
}

w3_usage_hook () {
	cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using Lemoteur.fr (www.lemoteur.fr)
Local options:
  -search=                      Specialized search on topic
  images  |  Images
  videos  |  Videos
  news    | News

  -i, -images                   Image Search (same as -search=images)
  -v, -videos                   Video Search (same as -search=videos)
  -n, -news                     News Search (same as -search=news)
EOF
		w3_global_usage
}

w3_parse_option_hook () {
		opt="$1"
		optarg="$2"
		case "$opt" in
		-r*=*)      setopt   SURFRAW_lemoteur_results "$optarg" ;;
		-s*=*)      setopt   SURFRAW_lemoteur_search  "$optarg" ;;
		-i*)        setopt   SURFRAW_lemoteur_search  images    ;;
		-v*)        setopt   SURFRAW_lemoteur_search  videos    ;;
		-n|-news)   setopt   SURFRAW_lemoteur_search  news      ;;
*) return 1 ;;
		esac
		return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments


url="http://lemoteur.orange.fr/?module=lemoteur&bhv="

case "$SURFRAW_lemoteur_search" in
		i*) url="${url}images" ;;
		n*) url="${url}actu"   ;;
		v*) url="${url}videos" ;;
		*)  url="${url}web_fr" ;;
esac

escaped_args=`w3_url_of_arg $w3_args`
url="${url}&kw=${escaped_args}"

w3_browse_url "$url"


