#!/bin/sh
#
# author: Wim Van Hoydonck
#
# elvis: springer	-- Search Springer for Books and Articles
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search-string]
Description:
  Search springer
Local options:
  -fields=FIELD			Subject field to search
           all              |   Seach all fields (default)
           author           |   Author name
           title            |   Title
           series           |   Series
           isbn             |   ISBN/ISSN

Examples:
  $w3_argv0 -fields=author featherstone
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if null "$w3_args"; then
    w3_browse_url "https://www.springer.com"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    url="https://link.springer.com/search?query=${escaped_args}"
    w3_browse_url "${url}"
fi

