#!/bin/sh
# $Id$
# elvis: yahoofinance		-- Search Yahoo Finance (www.finance.yahoo.com)
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_yahoofinance_results $SURFRAW_results
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search Yahoo Finance data (www.finance.yahoo.com)
				Environment: SURFRAW_yahoofinance_results
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-results=*) setopt   SURFRAW_yahoofinance_results $optarg	;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://www.finance.yahoo.com/"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_ul "https://finance.yahoo.com/quote/${escaped_args}"
fi
